// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljkcncyaniwzbkkzqyil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxqa2NuY3lhbml3emJra3pxeWlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0Nzg2OTIsImV4cCI6MjA2MzA1NDY5Mn0.W_e5_P12ufMOr6njggQygcp7GOvTMvopgqIlE2H_JL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);